In [1]:
import cv2 as cv
import numpy as np

In [9]:
classifier=cv.CascadeClassifier('haarcascade_frontalface_default.xml')
cam=cv.VideoCapture(0)
while True:
      _, img = cam.read()
      img = cv.flip(img,1)
      try:
        faces=classifier.detectMultiScale(img,1.1,8)
        for f in faces:                             # Going through Each Face Detected
            if f[-1] == max(faces[:,-1]):           # Finding the Face with Maximum Area
                break 

        if (len(faces) >= 1):                       # Drawing Rectange on the Face
            x = f[0] 
            y = f[1] 
            w = f[2]
            h = f[3]
        
            cv.rectangle(img,(x,y),(x+w,y+h),(0,150,200),3)
            face=img[y:y+h,x:x+w]
            face=cv.resize(face,(256,256))
      except:
            pass
    
            
      cv.imshow("Frame",img)
      cv.imshow("Frame1",face)
      print(faces)
      print('-----')
      if cv.waitKey(1)==27:
            cam.release()
            break



[[378 335 131 131]]
-----
[[380 328 136 136]]
-----
[[380 328 136 136]]
-----
[[383 331 131 131]]
-----
[[384 331 128 128]]
-----
[[383 330 130 130]]
-----
[[381 328 130 130]]
-----
[[381 328 130 130]]
-----
[[383 329 127 127]]
-----
[[381 326 134 134]]
-----
[[381 326 134 134]]
-----
[[380 327 135 135]]
-----
[[380 326 135 135]]
-----
[[382 331 127 127]]
-----
[[382 331 127 127]]
-----
[[378 330 132 132]]
-----
[[380 331 128 128]]
-----
[[380 331 128 128]]
-----
[[378 330 130 130]]
-----
[[377 330 132 132]]
-----
[[380 332 129 129]]
-----
[[380 332 129 129]]
-----
[[383 331 135 135]]
-----
[[386 334 132 132]]
-----
[[387 333 133 133]]
-----
[[387 336 134 134]]
-----
[[387 336 134 134]]
-----
[[392 337 131 131]]
-----
[[391 335 134 134]]
-----
[[391 335 134 134]]
-----
()
-----
[[391 337 132 132]]
-----
[[389 338 133 133]]
-----
[[389 338 133 133]]
-----
[[391 337 131 131]]
-----
[[391 336 133 133]]
-----
[[390 336 134 134]]
-----
[[390 336 134 134]]
-----
[[390 336 131 131]]
-----
[[3

Face detecting and applying black masking

In [10]:
import cv2 as cv
import numpy as np

classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:
        if f[-1] == max(faces[:,-1]):
            break

    x = f[0] 
    y = f[1] 
    w = f[2]
    h = f[3]

    face = img[y:y+h, x:x+w]
    
    black = np.zeros((face.shape), dtype = int)
    
    img[y:y+h, x:x+w] = black

    cv.imshow('Frame'  , img )
    cv.imshow('Face'   , face)
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

In [11]:
import cv2 as cv
import numpy as np

classifier = cv.CascadeClassifier('haarcascade_frontalface_default.xml')
cam = cv.VideoCapture(0)

while True:
    
    _, img = cam.read()
    img = cv.flip(img,1)
    
    faces = classifier.detectMultiScale(img, 1.1, 5)
    
    for f in faces:
        if f[-1] == max(faces[:,-1]):
            break

    x = f[0] 
    y = f[1] 
    w = f[2]
    h = f[3]
    
    circle_x = x + int(w/2)
    circle_y = y + int(h/2)
    
    cv.circle(img, (circle_x, circle_y), int(w/1.7), (110,180,68),-1)

    cv.imshow('Frame'  , img )
    
    if cv.waitKey(1) == 27:
        cam.release()
        break

: 